apiVersion: v1
kind: Namespace
metadata:
  name: clusterip-app
---
apiVersion: v1
kind: Pod
metadata:
  namespace: clusterip-app
  name: clusterip-pod
  labels:
    app.kubernetes.io/name: clusterip-app
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  namespace: clusterip-app
  name: clusterip-service
spec:
  selector:
    app.kubernetes.io/name: clusterip-app
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: http-web-svc

