apiVersion: v1
kind: Namespace
metadata:
  name: nodeport-app
---
apiVersion: v1
kind: Pod
metadata:
  namespace: nodeport-app
  name: nodeport-pod
  labels:
    app.kubernetes.io/name: nodeport-app
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 8080
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  namespace: nodeport-app
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nodeport-app
  ports:
  - name: web
    port: 8080
    targetPort: http-web-svc
    nodePort: 30007

